user:
  page: 1
  size: 80
  name_length: 50
  email_length: 255
  password_length: 6
  size_image: 50
  per_pag: 20
  hourss: 2
  maximum: 140
  size_micro: 50
  size_info: 50
  size_picture: 5
sessions:
  checked: "1"
micropost:
  picture_type: "image/jpeg,image/gif,image/png"